export const KAFKA_BROKER = process.env.KAFKA_BROKER || 'localhost:9092';
export const KAFKA_APP = process.env.KAFKA_APP || 'streets-demo-app';
export const KAFKA_TOPIC_CITIES = process.env.KAFKA_TOPIC_CITIES || 'topic-cities';
export const KAFKA_TOPIC_CITIES_THRESHOLD = process.env.KAFKA_TOPIC_CITIES_THRESHOLD || 1
export const KAFKA_TOPIC_CITIES_DLQ = process.env.KAFKA_TOPIC_CITIES_DLQ || 'topic-cities-dlq';
export const KAFKA_TOPIC_STREETS = process.env.KAFKA_TOPIC_STREETS || 'topic-streets';
export const KAFKA_TOPIC_STREETS_THRESHOLD = process.env.KAFKA_TOPIC_STREETS_THRESHOLD || 1;
export const KAFKA_TOPIC_STREETS_DLQ = process.env.KAFKA_TOPIC_STREETS_DLQ || 'topic-streets-dlq';
export const KAFKA_CONSUMER_GROUP = process.env.KAFKA_TOPIC_STREETS || 'topic-streets';
export const MONGO_DSN = process.env.MONGO_DSN || 'mongodb://localhost:27017';
export const MONGO_DB_NAME = process.env.MONGO_DB_NAME || 'streetDB';
export const MONGO_COLLECTION = 'streets';
export const PROMETHEUS_METRICS_PORT = process.env.PROMETHEUS_METRICS_PORT || 8080;
