version: 2
updates:
  # NPM (JavaScript dependencies)
  - package-ecosystem: "npm"
    directory: "/crawler"  # Location of package.json in the microservice directory
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"  # Check for updates every day
    commit-message:
      prefix: "npm"
    target-branch: "main" # Optional: specify the target branch
