networks:
  default:
    driver: bridge
    # prevent conflict with openVPN connection, use dedicated subnet
    ipam:
      config:
        - subnet: 172.16.57.0/24

services:
  pub:
    build:
      context: ./pub
      dockerfile: Dockerfile
    restart: no
    env_file:
      - .env
    depends_on:
      - redpanda
    networks:
      - default

  sub:
    build:
      context: ./sub
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    expose:
      - "8080"
    depends_on:
      - redpanda
      - redis
    networks:
      - default

