global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090

  - job_name: 'crawler'
    dns_sd_configs:
      - names:
          - 'crawler'
        type: 'A'
        port: 8080

rule_files:
  - "/etc/prometheus/rules/*.yml"  # Define your alerting rules here
