{
 "title": "Cadvisor exporter",
 "description": "Simple exporter for cadvisor only",
 "tags": [
  "cadvisor",
  "docker"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU / Usage (User & System)",
     "type": "timeseries",
     "description": "This metric measures the total CPU time consumed by the container across all its cores, combining both system and user time. It provides an overall picture of CPU usage.\n\n**Use Cases:**\n\n* It's a common metric to gauge overall CPU consumption per container.\n* Useful for setting alert thresholds to prevent over-utilization of CPU resources.\n* Often used in conjunction with other CPU metrics for trend analysis and capacity planning.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name) * 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "CPU / User",
     "type": "timeseries",
     "description": "This metric records the cumulative time spent by the container's CPU in user mode. User mode represents time spent executing application code rather than operating system kernel code.\n\n**Use Cases:**\n\n* Useful for analyzing the CPU time consumed by applications and processes within the container itself.\n\n* High values can indicate that the application is performing significant computation, making it suitable for performance profiling and optimization.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name) *100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "CPU / System",
     "type": "timeseries",
     "description": "This metric records the cumulative time spent by the container's CPU in system (kernel) mode. System mode represents time spent on kernel-level operations, such as handling I/O requests or managing system calls.\n\n**Use Cases:**\n\n* Useful to identify when containers are spending too much time in the kernel, which could indicate inefficiencies in system calls or potential issues with I/O operations.\n* Monitoring this can help detect whether excessive system overhead affects container performance.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_system_seconds_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name) *100",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory / Usage Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage Bytes",
     "type": "timeseries",
     "description": "Total memory usage, including all memory in use by the container (active, cached, etc.). This provides a high-level view of memory consumption.\n\n**Use Cases:**\n\n* Useful for tracking overall memory footprint.\n* Allows you to monitor and manage the container’s total memory consumption and detect any sudden increases that might indicate memory leaks.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Working Set",
     "type": "timeseries",
     "description": "Memory that is actively used by the container, excluding cache and unused memory. This shows the actual memory demand of the container.\n\n**Use Cases:**\n\n* Indicates the real memory demand of a container.\n* Helps prevent over-provisioning, as this metric focuses on memory actually being used for active processes rather than cached or unused memory.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Max Usage Bytes",
     "type": "timeseries",
     "description": "Peak memory usage since the container started. This helps in understanding historical maximum memory demand, useful for right-sizing containers.\n\n**Use Cases:**\n\n* Useful for capacity planning and identifying if a container’s memory usage spikes close to its limits.\n* Helps you assess historical memory demands and adjust container memory allocation accordingly.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_max_usage_bytes{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory / Detailed Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Resident Set Size",
     "type": "timeseries",
     "description": "Resident Set Size memory, representing non-swappable physical memory used by the container. This is memory that is actively in use and cannot be swapped out.\n\n**Use Cases:**\n\n* Shows memory that cannot be swapped to disk and is essential for the container’s operation.\n* Helpful to monitor for assessing memory pressure, as high RSS usage may mean the container is approaching its memory limit.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_rss{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Cached",
     "type": "timeseries",
     "description": "Cached memory, which includes data the container has used and stored in RAM for faster access. This memory can be freed if necessary.\n\n**Use Cases:**\n\n* Cached memory can be freed when needed, so high cache usage is generally not a concern.\n* Monitoring cache usage helps distinguish between memory actively in use and memory that can be freed.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_cache{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Mapped File",
     "type": "timeseries",
     "description": "Memory used for memory-mapped files, often used for accessing large files quickly. This provides insight into specific types of memory allocation used by the container.\n\n**Use Cases:**\n\n* Useful in understanding memory consumption related to memory-mapped file usage, common in applications that access large files frequently.\n* Allows fine-tuning if memory-mapped files significantly contribute to memory usage.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_mapped_file{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory / System-Level Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Kernel Usage",
     "type": "timeseries",
     "description": "Memory used by kernel processes on behalf of the container, such as system calls or kernel space processes.\n\n**Use Cases:**\n\n* Helpful in monitoring memory consumed by kernel processes on behalf of the container.\n* High kernel memory usage might suggest a high rate of system calls or other kernel-intensive operations within the container.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_kernel_usage{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Swap",
     "type": "timeseries",
     "description": "Amount of swap memory used by the container, indicating when it exceeds physical memory limits.\n\n**Use Cases:**\n\n* Indicates when the container has exceeded its physical memory limits and is using swap, which can lead to performance degradation.\n* High swap usage can indicate that more RAM should be allocated or that the container’s memory limits should be adjusted.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_swap{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory / Limit Breaches and Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Allocation Failures Count",
     "type": "timeseries",
     "description": "Count of memory allocation failures due to reaching memory limits. Useful for identifying if the container’s memory settings are too restrictive.\n\n**Use Cases:**\n\n* Helps in identifying memory bottlenecks in real-time.\n* Provides insight into whether memory limits are too restrictive for the container’s needs.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(rate(container_memory_failcnt{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Allocation Failures Total",
     "type": "timeseries",
     "description": "Total count of all memory allocation failures, offering a broader view of memory pressure within the container.\n\n**Use Cases:**\n\n* Useful for detecting memory pressure within the container, indicating when it couldn’t allocate more memory.\n* Helps troubleshoot memory limits and evaluate if more memory should be allocated to prevent application failures.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(rate(container_memory_failures_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network / Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Received Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sent Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network / Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packets Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Packets Sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_packets_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network / Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_errors_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Errors Sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_errors_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Packets dropped on receiving",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_packets_dropped_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Packets dropped on sending",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_packets_dropped_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block I/O (Input/Output)",
     "type": "timeseries",
     "description": "Cumulative I/O usage for block devices, typically representing the number of I/O operations or the amount of data (in bytes) read from or written to storage devices associated with the container.\n\n**Use Cases:**\n\n* Performance Monitoring: Helps monitor storage performance, especially important for I/O-intensive applications that frequently read and write data to disk.\n* Troubleshooting: High values in block I/O metrics may indicate heavy disk usage, which could lead to performance bottlenecks, especially in shared or limited storage environments.\n* Capacity Planning: Useful for understanding the container's disk utilization patterns and planning resource allocation based on usage trends.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_blkio_device_usage_total{name=~\"$container\",name=~\".+\"}[$__rate_interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem / Capacity and Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem / Limit",
     "type": "timeseries",
     "description": "Total available filesystem space for the container in bytes.\n\n**Use Cases:**\n\n* Capacity Planning: Useful for planning resource allocation to prevent overuse.\n* Monitoring: Tracks the total storage capacity to ensure sufficient space is available for container operations.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_fs_limit_bytes{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Usage",
     "type": "timeseries",
     "description": "Total filesystem space currently in use by the container in bytes.\n\n**Use Cases:**\n\n* Usage Tracking: Helps monitor storage consumption trends.\n* Troubleshooting: Detects overuse that could lead to storage exhaustion.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Total Inodes",
     "type": "timeseries",
     "description": "Total inodes available in the filesystem.\n\n**Use Cases:**\n\n* Capacity Planning, Monitoring.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(container_fs_inodes_total{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Free Inodes",
     "type": "timeseries",
     "description": "Free inodes available in the filesystem.\n\n**Use Cases:**\n\n* File System Health, Troubleshooting.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(container_fs_inodes_free{name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem / Read Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem / Total Read Operations",
     "type": "timeseries",
     "description": "Total number of read operations.\n\n**Use Cases:**\n\n* Read Activity Monitoring\n* Performance Tuning.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Bytes Read",
     "type": "timeseries",
     "description": "Total bytes read.\n\n**Use Cases:**\n\n* Data Transfer Analysis, Resource Optimization.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Total Read Time",
     "type": "timeseries",
     "description": "Total time spent on read operations.\n\n**Use Cases:**\n\n* Performance Monitoring, Troubleshooting.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_read_seconds_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Merged Reads",
     "type": "timeseries",
     "description": "Total merged read operations.\n\n**Use Cases:**\n\n* Efficiency Tracking, Troubleshooting.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_merged_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Sectors Read",
     "type": "timeseries",
     "description": "Total sectors read.\n\n**Use Cases:**\n\n* Storage Analysis, Optimization.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "sectors" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_sector_reads_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem / Write Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem / Total Write Operations",
     "type": "timeseries",
     "description": "Total write operations.\n\n**Use Cases:**\n\n* Write Activity Monitoring, Performance Optimization.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Bytes Written",
     "type": "timeseries",
     "description": "Total bytes written.\n\n**Use Cases:**\n\n* Data Transfer Analysis, Resource Planning.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Total Write Time",
     "type": "timeseries",
     "description": "Time spent on writes.\n\n**Use Cases:**\n\n* Performance Monitoring, Troubleshooting.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_write_seconds_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Merged Writes",
     "type": "timeseries",
     "description": "Total merged writes.\n\n**Use Cases:**\n\n* Efficiency Tracking, Optimization.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_merged_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Sectors Written",
     "type": "timeseries",
     "description": "Total sectors written.\n\n**Use Cases:**\n\n* Storage Tuning, Performance Analysis.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "sectors" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_sector_writes_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem / Performance and I/O Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem / Current I/O Ops",
     "type": "timeseries",
     "description": "Number of ongoing I/O operations.\n\n**Use Cases:**\n\n* I/O Load Monitoring, Troubleshooting.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum(container_fs_io_current{name=~\"$container\", name=~\".+\"}) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Total I/O Time",
     "type": "timeseries",
     "description": "Time spent on all I/O operations.\n\n**Use Cases:**\n\n* Performance Analysis, Troubleshooting.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_io_time_seconds_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Filesystem / Weighted I/O Time",
     "type": "timeseries",
     "description": "Weighted I/O time that considers both duration and volume.\n\n**Use Cases:**\n\n* Comprehensive I/O Analysis, Optimization.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_io_time_weighted_seconds_total{name=~\"$container\", name=~\".+\"}[$__rate_interval])) by (name)\r\n",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}